version: "3"

services:
  postgres:
    image: "postgres:9.5"
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  app:
    depends_on:
      - "postgres"
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/onebittwitter
      - gems:/gems

volumes:
  postgres:
  gems: